### PR TITLE
fix: Add type annotations to `get_object_or_None()`

### LINKED ISSUE #103: Possible to add support for types?
I have been enjoying using `get_object_or_None` all over my project in place of lazy incorrect `.first()` calls, and it's really great. However, it has the downside of losing the information about the object's type. Pyright tells me the returned type is `Unknown | None`, even though I know it has to be the corresponding type of the `Model | QuerySet | BaseManager` that I passed as `klass`.

image

### PR DESCRIPTION
**Pull request by tylerlaprade**
Fixes #103 

#### Pyright recognizes a `Model` type
image

#### Pyright rejects a non-model type
image

#### Pyright rejects an instance of a model in place of the type
image

#### Pyright accepts a `BaseManager`
image

#### Pyright accepts a `QuerySet`
image

### CODE REVIEW

**Review by skorokithakis — APPROVED** [review]

**Comment by skorokithakis** [comment]
Sorry for the delay! Which versions does this work with? Would you mind changing the supported versions in the setup file?

**Comment by tylerlaprade** [comment]
Sure, happy to do that, just not sure where to look!

**Comment by skorokithakis** [comment]
I'm fine to drop support for older versions and only support 3.6+, but there's a specifier you use in the `setup.py` to tell it which Python versions you want to support, and I don't remember the syntax offhand. Would you happen to remember what I'm talking about?

**Comment by tylerlaprade** [comment]
As far as I can tell, `'Programming Language :: Python :: 3.6',` is all we need in `setup.py`.

However, I just tested and found that this simpler syntax for generic types only became available in Python 3.12. If we want to support 3.10 and 3.11, we'd have to change it to use the older `TypeVar` syntax, like so:
`T = TypeVar('T', bound=CondorBaseModel)`.

To go earlier than 3.9, we'd have to change the union type syntax of the return type from `T | None` to `Union[T, None]` (I'm still trying to confirm if this is right). This would give us 3.5-3.9.

To go all the way back to 3.0, we would simply have to replace `from typing import TypeVar` with `from typing_extensions import TypeVar`. If we're already making the switch to `TypeVar`, this wouldn't be a big deal.

I have not checked what it would take to maintain Python 2.0 compatibility, but I can look it up if desired.

image

**Comment by skorokithakis** [comment]
I think 3.5+ is fine, anything past that might be a bit too new. I don't mean the trove classifier, I meant [the `python_requires` directive](https://packaging.python.org/en/latest/guides/dropping-older-python-versions/#specify-the-version-ranges-for-supported-python-distributions).

**Comment by tylerlaprade** [comment]
Hi, sorry for the delay, I was on paternity leave. I believe this addresses all the problems.

**Review by skorokithakis — APPROVED** [review]
Thank you, and congratulations!

**Pull request merged**
