### PR TITLE
Run tests against latest micro version of Django for each release

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by skorokithakis** [comment]
Ah, good call. Doesn't `~=` work?

**Comment by jdufresne** [comment]
> Doesn't ~= work?

I don't think that is equivalent. From the [pip docs](https://pip.pypa.io/en/stable/reference/pip_install/#example-requirements-file):

> Mopidy-Dirble ~= 1.1        # Compatible release. Same as >= 1.1, == 1.*

From my own experiment:

```
$ pip install 'Django~=1.9'
Collecting Django~=1.9
  Using cached Django-1.10.5-py2.py3-none-any.whl
Installing collected packages: Django
Successfully installed Django-1.10.5
```

**Comment by jdufresne** [comment]
The following looks to work, `'Django~=1.9.0'`. Would you prefer that syntax?

```
$ pip install 'Django~=1.9.0'
Collecting Django~=1.9.0
  Using cached Django-1.9.12-py2.py3-none-any.whl
Installing collected packages: Django
Successfully installed Django-1.9.12
```

**Comment by skorokithakis** [comment]
Yes, that's what I meant. Sorry. I always use `~=1.9.0` because it's immediately clear which minor version you're targeting.

**Comment by jdufresne** [comment]
Updated with your suggestion. Let me know if that is what you had in mind. Thanks.

**Comment by skorokithakis** [comment]
Looks good, thank you!

**Pull request merged**
