### PR TITLE
Solve: SubfieldBase has been deprecated in Django 1.9 and will be removed in Django 1.10

### PR DESCRIPTION
**Pull request by edelvalle**

### CODE REVIEW

**Comment by skorokithakis** [comment]
This makes tests fail, is there any way we can implement this forwards-compatibly?

**Comment by edelvalle** [comment]
I'm working on it right now... ;) 
Give me a while...

**Comment by skorokithakis** [comment]
Yaaay!

**Comment by skorokithakis** [comment]
Looks good to me, a few questions:

1) Have you tested this locally, and is everything okay with that?
2) Are you ready for me to merge this, or do you need me to wait?

Thanks for your help!

**Comment by edelvalle** [comment]
I'm using it and everything looks fine to me.

But this migration to Django >1.9 needs more care because when I run the tests there are some other warnings... 

```
Creating test database for alias 'default'...
/home/xigurat/.virtualenvs/mym/lib/python3.5/site-packages/django/test/testcases.py:230: RemovedInDjango110Warning: SimpleTestCase.urls is deprecated and will be removed in Django 1.10. Use @override_settings(ROOT_URLCONF=...) in AJAXRequestTestCase instead.
  self._urlconf_setup()

/home/xigurat/ownCloud/src/myonlinemediator/django-annoying/annoying/tests/urls.py:19: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  (r'^render-to-content-type-positional/$', views.render_to_content_type_positional),

......./home/xigurat/.virtualenvs/mym/lib/python3.5/site-packages/django/test/testcases.py:230: RemovedInDjango110Warning: SimpleTestCase.urls is deprecated and will be removed in Django 1.10. Use @override_settings(ROOT_URLCONF=...) in RenderToTestCase instead.
  self._urlconf_setup()

/home/xigurat/.virtualenvs/mym/lib/python3.5/site-packages/django/shortcuts.py:45: RemovedInDjango110Warning: The context_instance argument of render_to_string is deprecated.
  using=using)

...
----------------------------------------------------------------------
Ran 10 tests in 0.045s

OK
Destroying test database for alias 'default'...
```

But this is good to go!

**Comment by skorokithakis** [comment]
Hmm, those warnings seem to all be in tests, except for the last one, which is more urgent and will need to be fixed.

Thanks again for your help!

**Pull request merged**
