### PR TITLE
AutoSingleRelatedObjectDescriptor atomic context

### LINKED ISSUE #20: django.db.utils.IntegrityError with AutoSingleRelatedObjectDescriptor
the `__get__` function is not thread safe.

### PR DESCRIPTION
**Pull request by jlhawn**
Adds django.db.transaction.atomic context manager to
AutoSingleRelatedObjectDescriptor.__get__

closes #20

### CODE REVIEW

**Comment by savingschampion** [comment]
@skorokithakis can you make the change please? I don't think he's updating the PR and it's still an issue

**Comment by skorokithakis** [comment]
Sure, but I'm a bit confused as to what the issue is. Is it the write-after-read that may have another process write to it after the read?

**Comment by savingschampion** [comment]
The issue is if two people cause this code to trigger together at the same time, in a multithreaded deployment. You can end up with both users getting the same PK, which then obviously errors for the second individual. Made PR #38 with these changes

**Comment by skorokithakis** [comment]
#38 supersedes this one, correct?

**Comment by savingschampion** [comment]
Correct :)

**Comment by skorokithakis** [comment]
Merged, thanks! Closing this one.

**Pull request closed without merging**
