### PR TITLE
django1.8 compatibility

### PR DESCRIPTION
**Pull request by fruitschen**
This is for #96 

I cannot cerate a pull request from tag to tag. 
So I created the PR from our v0.10.6-branch to their master branch. 
I hope this makes sense. 

Thanks,
Chen

### CODE REVIEW

**Comment by skorokithakis** [comment]
Looks good, thanks!

**Comment by skorokithakis** [comment]
Can you run pre-commit on it so the checks pass?

**Comment by skorokithakis** [comment]
Why closed?

**Comment by fruitschen** [comment]
Ah, that was an accident. Took me two commits to fix import order. So I recreated the branch to squash them. That caused github to automatically closing the PR.

**Pull request closed without merging**
