### PR TITLE
Drop support for unsupported, unmaintained versions of Django

### PR DESCRIPTION
**Pull request by jdufresne**
Django libraries should try to closely follow the upstream supported
versions. Older versions of Django are unspported and unmaintained including
security fixes. Removing support allows fewer workarounds for deprecated or
dropped features. Allows for a smaller test matrix.

See the link below for a description and timeline of supported versions.

https://www.djangoproject.com/download/#supported-versions

### CODE REVIEW

**Comment by skorokithakis** [comment]
Hmm, I'm not terribly keen on dropping support for no reason at all. If a certain new feature or fix requires jumping through hoops to have it supported on an obsolete version of Python or Django, then I'm fine with not going to that effort, but I don't think removing support just for removal's sake is worthwhile.

Does your PR include improvements for the current versions of Django? I see some App Registry changes in.

**Comment by jdufresne** [comment]
The code, as-is, contains many workarounds for multiple versions of Django. Some of these are to workaround deprecated features others to workaround internal API changes. I think the fewer of these workarounds required, the better for maintaining the codebase as the code becomes simpler and easier to comprehend. I've removed all workarounds I noticed in the PR.

Versions of Django before 1.8 are no longer supported upstream or maintained. This includes security issues. IMO, a Django library should not be endorsing a version of Django that may contain security issues.

Dropping old versions of Django makes testing much simpler. When I was working on other PRs, I regularly introduced bugs on old Python/Django combinations that I haven't used in years. Testing on some of these old combinations is cumbersome and difficult. Realizing my mistake often required a full, slow round trip of Travis CI..

As new versions of Django are release, a few of django-annoying features have become obsolete as they're now builtin. For example, the `smart_if` tag is now the default behavior of the `if` tag. As a result, I've removed it in the PR. Another example, the `@autorstrip()` decorator is now the default behavior of `CharField` starting with Django 1.9. I think it makes sense to encourage the use of upstream features once they land to reduce the maintenance, code size, and duplication of this library.

Those choosing to stick to old versions of Django can also stick to old versions of django-annoying through requirements.txt.

Ultimately, up to you on how you prefer to proceed. If you decide not to merge this PR, no problem, feel free to close.

Thanks.

**Comment by skorokithakis** [comment]
Hmm, I agree with you on all counts, except that I believe that deprecation should happen when the old code gets in the way of new features. For example, if one implements a new feature and finds that it takes too long to test parts of the obsolete code, removing those parts is warranted.

However, as you say, people can always use the last version that supported their version of Python/Django, so I guess we aren't really depriving anyone of any functionality. I'll think about this some more and return, thanks again!

**Comment by skorokithakis** [comment]
Alright, you're right, this cleanup should be merged. Thank you for your help! Is everything working properly in your tests?

**Pull request merged**
